# Generated by Django 5.1.8 on 2025-04-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('review', models.CharField(max_length=300, verbose_name='Отзыв')),
            ],
        ),
    ]
